application: d08h
version: 4
runtime: python
api_version: 1

handlers: 
- url: /stylesheets
  static_dir: stylesheets
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /trash.gif
  static_files: static/trash.gif
  upload: static/trash.gif

- url: /tweet_this.png
  static_files: static/tweet_this.png
  upload: static/tweet_this.png
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /update
  script: twimgr.py
  login: required

- url: /user
  script: twimgr.py
  login: required
  
- url: /u
  script: twimgr.py
  login: required

- url: /delete
  script: twimgr.py
  login: required
  
- url: .*
  script: twimgr.py


