application: d08h
version: 2
runtime: python
api_version: 1

handlers: 
- url: /stylesheets
  static_dir: stylesheets
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /update
  script: main.py
  login: required

- url: /user
  script: main.py
  login: required
  
- url: /u
  script: main.py
  login: required
  
- url: .*
  script: main.py


